'use client'

import { LightBulbIcon, ExclamationTriangleIcon, ArrowTrendingUpIcon } from '@heroicons/react/24/outline'

interface Insight {
  id: string
  type: 'tip' | 'warning' | 'opportunity'
  title: string
  description: string
  priority: 'low' | 'medium' | 'high'
}

export function AIInsights() {
  // Mock insights - will be generated by AI
  const insights: Insight[] = [
    {
      id: '1',
      type: 'opportunity',
      title: 'High engagement detected',
      description: '5 prospects from Finance sector showing strong buying signals',
      priority: 'high',
    },
    {
      id: '2',
      type: 'tip',
      title: 'Optimize send times',
      description: 'Your emails perform 30% better when sent at 10 AM EST',
      priority: 'medium',
    },
    {
      id: '3',
      type: 'warning',
      title: 'Low reply rate',
      description: 'Consider updating your email templates for better engagement',
      priority: 'low',
    },
  ]
  
  const getIcon = (type: Insight['type']) => {
    switch (type) {
      case 'tip':
        return <LightBulbIcon className="h-5 w-5 text-blue-500" />
      case 'warning':
        return <ExclamationTriangleIcon className="h-5 w-5 text-yellow-500" />
      case 'opportunity':
        return <ArrowTrendingUpIcon className="h-5 w-5 text-green-500" />
    }
  }
  
  return (
    <div className="space-y-4">
      {insights.length === 0 ? (
        <p className="text-sm text-gray-500">No insights available</p>
      ) : (
        insights.map((insight) => (
          <div key={insight.id} className="flex items-start space-x-3">
            <div className="flex-shrink-0 mt-1">
              {getIcon(insight.type)}
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-gray-900">
                {insight.title}
              </p>
              <p className="text-sm text-gray-500">
                {insight.description}
              </p>
            </div>
          </div>
        ))
      )}
    </div>
  )
}